Algoritmo "deposito e saldo"
// Logica de programação
// Marcos Monteiro 
// Descrição   : Aqui você descreve o que o programa faz! (função)
// Autor(a)    : Bethânia
// Data atual  : 01/05/2022
Var
deposito, saldo : real


Inicio
escreval("Seu saldo atual é de R$ 200,00")
escreval("quanto deseja depositar: R$ ")
leia(deposito)
escreval("Saldo inicial: R$ 200")
escreval("Depositado: R$ ",deposito)
escreval("Saldo atualizado: R$ ",(200 + deposito))



Fimalgoritmo