Algoritmo "2 - NOME_e_ENDEREÇO"
// Logica de programação
// Marcos Monteiro
// Descrição   : Aqui você descreve o que o programa faz! (função)
// Autor(a)    : Nome do(a) aluno(a)
// Data atual  : 01/05/2022
Var
nome : caractere
endereco: caractere


Inicio
escreva ("Digite seu nome: ")
leia(nome)
escreva ("Qual seu endereço: ")
leia(endereco)
escreva("Nome: ",nome)
escreva("Endereço: ",endereco)

Fimalgoritmo