Algoritmo "AULA 09 - TABUADA COM ENQUANTO"
// Logica de programação
// Marcos Monteiro 
// Descrição   : Aqui você descreve o que o programa faz! (função)
// Autor(a)    : Bethânia Freitas
// Data atual  : 23/05/2022
Var
j, numero : inteiro


Inicio
escreval("---TABUADA---")
escreval("Digite um numero para ver sua tabuada: ")
leia(numero)
j<- 1
    enquanto j < 11 faca
       escreval( numero, " x ", j, " = ",(numero*j))
       j<- j+1
    fimenquanto




Fimalgoritmo