Algoritmo "AULA 08 - TABUADA"
// Logica de programação
// Marcos Monteiro 
// Descrição   : Aqui você descreve o que o programa faz! (função)
// Autor(a)    : Bethânia
// Data atual  : 23/05/2022
Var
numero: inteiro
sequencia: inteiro


Inicio
sequencia<- 1

escreval("---TABUADA---")
escreval("Digite o numero para ver a tabuada dele:")
leia (numero)

para sequencia de 1 ate 10  faca
     escreval(numero, " x ", sequencia, " = ", (numero*sequencia))
fimpara


Fimalgoritmo