Algoritmo "Aula 06 - idade"
// Logica de programação
// Marcos Monteiro 
// Descrição   : Aqui você descreve o que o programa faz! (função)
// Autor(a)    : Bethânia
// Data atual  : 01/05/2022
Var
  idade : inteiro


Inicio
 escreval("Digite sua idade: ")
 leia(idade)
 
 se idade <18 então
 escreval("Você é menor de idade")
 senao
 se idade < 60 então
 escreval("Você é adulto")
 senão
 escreval("Você é idoso")
 fimse
 fimse


Fimalgoritmo