Algoritmo "AULA 10 - Imprime -Repita - Interrompa"
// Logica de programação
// Marcos Monteiro 
// Descrição   : Aqui você descreve o que o programa faz! (função)
// Autor(a)    : Bethânia Freitas
// Data atual  : 25/05/2022
Var
   j : inteiro


Inicio
   escreval("Escrevendo de 1 a 10 usando repita e interrompa")
   j <- 1
   repita
         escreval(j)
         j <- j+1
         se j = 5    entao
            interrompa
         fimse
   ate j > 10


Fimalgoritmo