Algoritmo "AULA 10 - DE 1 ATE 10 - REPITA ATE"
// Logica de programação
// Marcos Monteiro 
// Descrição   : Aqui você descreve o que o programa faz! (função)
// Autor(a)    : Bethânia Freitas
// Data atual  : 25/05/2022
Var
 j : inteiro


Inicio
    escreval("Escreva de 1 até 10 usando o Repita Ate")
    j <- 1
    repita
          escreval(j)
          j <- j+1
    ate j > 10
          


Fimalgoritmo