Algoritmo "AULA 10 - SOMA DOS 100 PRIMEIROS NUMEROS INTEIROS"
// Logica de programação
// Marcos Monteiro 
// Descrição   : Aqui você descreve o que o programa faz! (função)
// Autor(a)    : Bethânia Freitas
// Data atual  : 25/05/2022
Var
contador : inteiro

soma: inteiro



Inicio

contador <- 0

para contador de 0 ate 100 faca
      soma <- soma + contador


      contador <- contador + 1
fimpara
escreval("A soma dos 100 primeiros numeros inteiros é de ", soma)





Fimalgoritmo